#!/usr/bin/env bash
# Version bump for kavach (Cyrius-native).
#
# Updates the version sources that actually exist in this repo:
#   1. VERSION              — single source of truth
#   2. CHANGELOG.md         — inserts a dated section after [Unreleased]
#   3. src/main.cyr         — the demo banner literal ("kavach vX.Y.Z — …")
#   4. dist/kavach.cyr      — regenerated via `cyrius distlib` (its bundle
#                             header stamps the version), if the toolchain
#                             is on PATH
#
# Notes:
#   - cyrius.cyml reads the version via `version = "${file:VERSION}"`, so it
#     needs no edit.
#   - src/main.cyr carries the demo banner literal "kavach vX.Y.Z" (step 3).
#     ⛔ This file used to claim kavach had NO embedded version literal. That was
#     FALSE and had been since v3.2.0: the banner was introduced then and never
#     bumped again, so the in-tree binary printed "kavach v3.2.0" for nine
#     releases while VERSION read 3.11.13. Nothing caught it — CI's smoke test
#     greps only for "kavach v", and the banner is not in dist/ (src/main.cyr is
#     excluded from [lib].modules), so no consumer ever saw the wrong number.
#     Corrected at v3.11.14 by bumping the literal AND making this script own it.
#     As of v3.6.0 kavach DOES ship a source-level library bundle
#     (`dist/kavach.cyr` + `dist/kavach.deps`, generated by `cyrius distlib`
#     from the `[lib]` modules) — the bundle header carries the version, so a
#     bump must regenerate it. CI gates dist freshness (see .github/workflows/
#     ci.yml "Verify dist bundle fresh").
#   - Git is the user's: this script touches files only, never runs git.
#
# (Replaced the Rust-era script that bumped VERSION + Cargo.toml; kavach has no
#  Cargo.toml since the Cyrius port, so the old script died mid-run.)
set -euo pipefail

if [ $# -ne 1 ]; then
    echo "Usage: $0 <new-version>"
    echo "Current: $(cat "$(dirname "${BASH_SOURCE[0]}")/../VERSION" 2>/dev/null || echo '?')"
    exit 1
fi

NEW="$1"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OLD="$(tr -d '[:space:]' < "$ROOT/VERSION")"

echo "$NEW" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+([-+][0-9A-Za-z.]+)?$' || {
    echo "error: '$NEW' is not valid semver" >&2
    exit 1
}

if [ "$NEW" = "$OLD" ]; then
    echo "Already at $OLD"
    exit 0
fi

echo "Bumping kavach $OLD -> $NEW"

# 1. VERSION
echo "$NEW" > "$ROOT/VERSION"
echo "  Updated VERSION"

# 2. CHANGELOG.md — insert a dated section right after [Unreleased] (idempotent).
#    Existing [Unreleased] bullets fall under the new version section; a fresh
#    empty [Unreleased] stays on top.
if [ -f "$ROOT/CHANGELOG.md" ]; then
    if grep -q "## \[$NEW\]" "$ROOT/CHANGELOG.md"; then
        echo "  CHANGELOG.md already has [$NEW] — left as-is"
    else
        sed -i "/## \[Unreleased\]/a\\
\\
## [$NEW] — $(date +%Y-%m-%d)" "$ROOT/CHANGELOG.md"
        echo "  Updated CHANGELOG.md"
    fi
fi

# 3. src/main.cyr — the demo banner literal. Anchored on the "kavach v<semver> —"
#    shape so it cannot match prose elsewhere in the file; idempotent.
if [ -f "$ROOT/src/main.cyr" ]; then
    if grep -qE '"kavach v[0-9]+\.[0-9]+\.[0-9]+ ' "$ROOT/src/main.cyr"; then
        sed -i -E "s/\"kavach v[0-9]+\.[0-9]+\.[0-9]+ /\"kavach v$NEW /" "$ROOT/src/main.cyr"
        echo "  Updated src/main.cyr banner"
    else
        echo "  WARN: no 'kavach v<semver>' banner found in src/main.cyr"
    fi
fi

# 4. dist/ bundle — regenerate so the bundle header stamps $NEW. `cyrius
#    distlib` reads [lib].modules from cyrius.cyml and rewrites
#    dist/kavach.cyr + dist/kavach.deps. Best-effort: skip with a reminder
#    if the toolchain isn't on PATH (the CI freshness gate is the backstop).
if command -v cyrius >/dev/null 2>&1; then
    ( cd "$ROOT" && cyrius distlib >/dev/null 2>&1 ) \
        && echo "  Regenerated dist/kavach.cyr (cyrius distlib)" \
        || echo "  WARN: 'cyrius distlib' failed — regenerate dist/ manually"
else
    echo "  SKIP: cyrius not on PATH — run 'cyrius distlib' to refresh dist/ before committing"
fi

echo ""
echo "Done. The user owns git:"
echo "  git add -A && git commit -m \"bump to $NEW\" && git tag $NEW"
